extern const GeoLayout asha_Left_Hand_Open[];
extern const GeoLayout asha_Right_Hand_Open[];
extern const GeoLayout asha_Right_Hand_Peace[];
extern const GeoLayout asha_Right_Hand_Cap[];
extern const GeoLayout asha_Right_Hand_Wing_Cap[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_asha_Left_Hand_Open[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_asha_Right_Hand_Open[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_asha_Right_Hand_Peace[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_asha_Right_Hand_Cap[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_asha_Right_Hand_Wing_Cap[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt1[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_asha_Left_Hand_Open[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_asha_Right_Hand_Open[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_asha_Right_Hand_Peace[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_asha_Right_Hand_Cap[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_asha_Right_Hand_Wing_Cap[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt2[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_asha_Left_Hand_Open[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_asha_Right_Hand_Open[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_asha_Right_Hand_Peace[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_asha_Right_Hand_Cap[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_asha_Right_Hand_Wing_Cap[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt3[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2[];
extern const GeoLayout asha_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3[];
extern const GeoLayout asha_geo[];
extern Lights1 asha_pants_lights;
extern Lights1 asha_skin_lights;
extern Lights1 asha_belly_lights;
extern Lights1 asha_buckle_lights;
extern Lights1 asha_Metal__METAL__lights;
extern Lights1 asha_shirt_lights;
extern Lights1 asha_face_lights;
extern Lights1 asha_hair_lights;
extern Lights1 asha_Half_Closed_Eyes__SKIN__lights;
extern Lights1 asha_Closed_Eyes__SKIN__lights;
extern Lights1 asha_Dead_Eyes__SKIN__lights;
extern Lights1 asha_cuffs_lights;
extern Lights1 asha_spikes_lights;
extern u8 asha_asha_emblem_rgba16[];
extern u8 asha_Metal_Shade_rgba16_rgba16[];
extern u8 asha_Metal_Light_rgba16_rgba16[];
extern u8 asha_asha_face_open_rgba16[];
extern u8 asha_asha_face_half_rgba16[];
extern u8 asha_asha_face_closed_rgba16[];
extern u8 asha_asha_face_dead_rgba16[];
extern u8 asha_wing_2_rgba16[];
extern u8 asha_wing1_rgba16[];
extern Vtx asha_Butt_mesh_layer_1_vtx_0[92];
extern Gfx asha_Butt_mesh_layer_1_tri_0[];
extern Vtx asha_Butt_mesh_layer_1_vtx_1[113];
extern Gfx asha_Butt_mesh_layer_1_tri_1[];
extern Vtx asha_Butt_mesh_layer_1_vtx_2[12];
extern Gfx asha_Butt_mesh_layer_1_tri_2[];
extern Vtx asha_Butt_mesh_layer_4_vtx_0[8];
extern Gfx asha_Butt_mesh_layer_4_tri_0[];
extern Vtx asha_Torso_mesh_layer_1_vtx_0[42];
extern Gfx asha_Torso_mesh_layer_1_tri_0[];
extern Vtx asha_Torso_mesh_layer_1_vtx_1[61];
extern Gfx asha_Torso_mesh_layer_1_tri_1[];
extern Vtx asha_Torso_mesh_layer_1_vtx_2[12];
extern Gfx asha_Torso_mesh_layer_1_tri_2[];
extern Vtx asha_Head_DL_mesh_layer_1_vtx_0[30];
extern Gfx asha_Head_DL_mesh_layer_1_tri_0[];
extern Vtx asha_Head_DL_mesh_layer_1_vtx_1[15];
extern Gfx asha_Head_DL_mesh_layer_1_tri_1[];
extern Vtx asha_Head_DL_mesh_layer_1_vtx_2[180];
extern Gfx asha_Head_DL_mesh_layer_1_tri_2[];
extern Vtx asha_Left_Wing_DL_mesh_layer_4_vtx_0[4];
extern Gfx asha_Left_Wing_DL_mesh_layer_4_tri_0[];
extern Vtx asha_Left_Wing_DL_mesh_layer_4_vtx_1[4];
extern Gfx asha_Left_Wing_DL_mesh_layer_4_tri_1[];
extern Vtx asha_Right_Wing_DL_mesh_layer_4_vtx_0[4];
extern Gfx asha_Right_Wing_DL_mesh_layer_4_tri_0[];
extern Vtx asha_Right_Wing_DL_mesh_layer_4_vtx_1[4];
extern Gfx asha_Right_Wing_DL_mesh_layer_4_tri_1[];
extern Vtx asha_Left_Arm_Color_mesh_layer_1_vtx_0[39];
extern Gfx asha_Left_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx asha_Left_Forearm_mesh_layer_1_vtx_0[39];
extern Gfx asha_Left_Forearm_mesh_layer_1_tri_0[];
extern Vtx asha_Left_Forearm_mesh_layer_1_vtx_1[81];
extern Gfx asha_Left_Forearm_mesh_layer_1_tri_1[];
extern Vtx asha_Left_Forearm_mesh_layer_1_vtx_2[64];
extern Gfx asha_Left_Forearm_mesh_layer_1_tri_2[];
extern Vtx asha_Left_Hand_DL_mesh_layer_1_vtx_0[91];
extern Gfx asha_Left_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx asha_Left_Hand_DL_mesh_layer_1_vtx_1[48];
extern Gfx asha_Left_Hand_DL_mesh_layer_1_tri_1[];
extern Vtx asha_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_vtx_0[91];
extern Gfx asha_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_tri_0[];
extern Vtx asha_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_vtx_1[48];
extern Gfx asha_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_tri_1[];
extern Vtx asha_Right_Arm_Color_mesh_layer_1_vtx_0[39];
extern Gfx asha_Right_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx asha_Right_Forearm_mesh_layer_1_vtx_0[39];
extern Gfx asha_Right_Forearm_mesh_layer_1_tri_0[];
extern Vtx asha_Right_Forearm_mesh_layer_1_vtx_1[78];
extern Gfx asha_Right_Forearm_mesh_layer_1_tri_1[];
extern Vtx asha_Right_Forearm_mesh_layer_1_vtx_2[64];
extern Gfx asha_Right_Forearm_mesh_layer_1_tri_2[];
extern Vtx asha_Right_Hand_DL_mesh_layer_1_vtx_0[91];
extern Gfx asha_Right_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx asha_Right_Hand_DL_mesh_layer_1_vtx_1[48];
extern Gfx asha_Right_Hand_DL_mesh_layer_1_tri_1[];
extern Vtx asha_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_vtx_0[87];
extern Gfx asha_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_tri_0[];
extern Vtx asha_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_vtx_1[48];
extern Gfx asha_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_tri_1[];
extern Vtx asha_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_vtx_0[88];
extern Gfx asha_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_tri_0[];
extern Vtx asha_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_vtx_1[36];
extern Gfx asha_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_tri_1[];
extern Vtx asha_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_vtx_0[87];
extern Gfx asha_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_tri_0[];
extern Vtx asha_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_vtx_1[48];
extern Gfx asha_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_tri_1[];
extern Vtx asha_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_vtx_0[87];
extern Gfx asha_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx asha_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_vtx_1[48];
extern Gfx asha_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_tri_1[];
extern Vtx asha_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_vtx_0[8];
extern Gfx asha_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_tri_0[];
extern Vtx asha_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_vtx_1[8];
extern Gfx asha_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_tri_1[];
extern Vtx asha_Left_Thigh_Color_mesh_layer_1_vtx_0[39];
extern Gfx asha_Left_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx asha_Left_Leg_mesh_layer_1_vtx_0[54];
extern Gfx asha_Left_Leg_mesh_layer_1_tri_0[];
extern Vtx asha_Left_Leg_mesh_layer_1_vtx_1[21];
extern Gfx asha_Left_Leg_mesh_layer_1_tri_1[];
extern Vtx asha_Left_Shoe_mesh_layer_1_vtx_0[60];
extern Gfx asha_Left_Shoe_mesh_layer_1_tri_0[];
extern Vtx asha_Left_Shoe_mesh_layer_1_vtx_1[81];
extern Gfx asha_Left_Shoe_mesh_layer_1_tri_1[];
extern Vtx asha_Right_Thigh_Color_mesh_layer_1_vtx_0[39];
extern Gfx asha_Right_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx asha_Right_Leg_mesh_layer_1_vtx_0[54];
extern Gfx asha_Right_Leg_mesh_layer_1_tri_0[];
extern Vtx asha_Right_Leg_mesh_layer_1_vtx_1[21];
extern Gfx asha_Right_Leg_mesh_layer_1_tri_1[];
extern Vtx asha_Right_Shoe_DL_mesh_layer_1_vtx_0[60];
extern Gfx asha_Right_Shoe_DL_mesh_layer_1_tri_0[];
extern Vtx asha_Right_Shoe_DL_mesh_layer_1_vtx_1[81];
extern Gfx asha_Right_Shoe_DL_mesh_layer_1_tri_1[];
extern Gfx mat_asha_pants[];
extern Gfx mat_revert_asha_pants[];
extern Gfx mat_asha_skin[];
extern Gfx mat_revert_asha_skin[];
extern Gfx mat_asha_belly[];
extern Gfx mat_revert_asha_belly[];
extern Gfx mat_asha_buckle[];
extern Gfx mat_revert_asha_buckle[];
extern Gfx mat_asha_Metal__METAL_[];
extern Gfx mat_revert_asha_Metal__METAL_[];
extern Gfx mat_asha_shirt[];
extern Gfx mat_revert_asha_shirt[];
extern Gfx mat_asha_face[];
extern Gfx mat_revert_asha_face[];
extern Gfx mat_asha_hair[];
extern Gfx mat_revert_asha_hair[];
extern Gfx mat_asha_Half_Closed_Eyes__SKIN_[];
extern Gfx mat_revert_asha_Half_Closed_Eyes__SKIN_[];
extern Gfx mat_asha_Closed_Eyes__SKIN_[];
extern Gfx mat_revert_asha_Closed_Eyes__SKIN_[];
extern Gfx mat_asha_Dead_Eyes__SKIN_[];
extern Gfx mat_revert_asha_Dead_Eyes__SKIN_[];
extern Gfx mat_asha_Wing_Tip[];
extern Gfx mat_revert_asha_Wing_Tip[];
extern Gfx mat_asha_Wing_Base[];
extern Gfx mat_revert_asha_Wing_Base[];
extern Gfx mat_asha_cuffs[];
extern Gfx mat_revert_asha_cuffs[];
extern Gfx mat_asha_spikes[];
extern Gfx mat_revert_asha_spikes[];
extern Gfx asha_Butt_mesh_layer_1[];
extern Gfx asha_Butt_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Butt_mesh_layer_4[];
extern Gfx asha_Butt_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx asha_Torso_mesh_layer_1[];
extern Gfx asha_Torso_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Head_DL_mesh_layer_1[];
extern Gfx asha_Head_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Head_DL_mesh_layer_1_mat_override_Half_Closed_Eyes__SKIN__1[];
extern Gfx asha_Head_DL_mesh_layer_1_mat_override_Closed_Eyes__SKIN__2[];
extern Gfx asha_Head_DL_mesh_layer_1_mat_override_Dead_Eyes__SKIN__3[];
extern Gfx asha_Left_Wing_DL_mesh_layer_4[];
extern Gfx asha_Left_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx asha_Right_Wing_DL_mesh_layer_4[];
extern Gfx asha_Right_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx asha_Left_Arm_Color_mesh_layer_1[];
extern Gfx asha_Left_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Left_Forearm_mesh_layer_1[];
extern Gfx asha_Left_Forearm_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Left_Hand_DL_mesh_layer_1[];
extern Gfx asha_Left_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1[];
extern Gfx asha_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Right_Arm_Color_mesh_layer_1[];
extern Gfx asha_Right_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Right_Forearm_mesh_layer_1[];
extern Gfx asha_Right_Forearm_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Right_Hand_DL_mesh_layer_1[];
extern Gfx asha_Right_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1[];
extern Gfx asha_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1[];
extern Gfx asha_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1[];
extern Gfx asha_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1[];
extern Gfx asha_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4[];
extern Gfx asha_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx asha_Left_Thigh_Color_mesh_layer_1[];
extern Gfx asha_Left_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Left_Leg_mesh_layer_1[];
extern Gfx asha_Left_Leg_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Left_Shoe_mesh_layer_1[];
extern Gfx asha_Left_Shoe_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Right_Thigh_Color_mesh_layer_1[];
extern Gfx asha_Right_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Right_Leg_mesh_layer_1[];
extern Gfx asha_Right_Leg_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_Right_Shoe_DL_mesh_layer_1[];
extern Gfx asha_Right_Shoe_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx asha_material_revert_render_settings[];
