extern const GeoLayout asha_cap_6_Cap_Anim_State_Switch_opt1[];
extern const GeoLayout asha_cap_geo[];
extern Lights1 asha_cap_cuffs_lights;
extern Lights1 asha_cap_belt_gold_lights;
extern Lights1 asha_cap_buckle_lights;
extern u8 asha_cap_asha_emblem_rgba16[];
extern Vtx asha_cap_Cap_DL_mesh_layer_1_vtx_0[114];
extern Gfx asha_cap_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx asha_cap_Cap_DL_mesh_layer_1_vtx_1[72];
extern Gfx asha_cap_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx asha_cap_Cap_DL_mesh_layer_4_vtx_0[8];
extern Gfx asha_cap_Cap_DL_mesh_layer_4_tri_0[];
extern Gfx mat_asha_cap_cuffs[];
extern Gfx mat_revert_asha_cap_cuffs[];
extern Gfx mat_asha_cap_belt_gold[];
extern Gfx mat_revert_asha_cap_belt_gold[];
extern Gfx mat_asha_cap_buckle[];
extern Gfx mat_revert_asha_cap_buckle[];
extern Gfx asha_cap_Cap_DL_mesh_layer_1[];
extern Gfx asha_cap_Cap_DL_mesh_layer_4[];
extern Gfx asha_cap_material_revert_render_settings[];
