extern const GeoLayout asha_cap_6_Cap_Anim_State_Switch_opt1[];
extern const GeoLayout asha_cap_geo[];
extern Lights1 asha_cap_metal_gold_lights;
extern Lights1 asha_cap_belt_gold_lights;
extern Lights1 asha_cap_buckle_cap_lights;
extern Vtx asha_cap_Cap_DL_mesh_layer_1_vtx_0[89];
extern Gfx asha_cap_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx asha_cap_Cap_DL_mesh_layer_1_vtx_1[72];
extern Gfx asha_cap_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx asha_cap_Cap_DL_mesh_layer_1_vtx_2[8];
extern Gfx asha_cap_Cap_DL_mesh_layer_1_tri_2[];
extern Gfx mat_asha_cap_metal_gold[];
extern Gfx mat_revert_asha_cap_metal_gold[];
extern Gfx mat_asha_cap_belt_gold[];
extern Gfx mat_revert_asha_cap_belt_gold[];
extern Gfx mat_asha_cap_buckle_cap[];
extern Gfx mat_revert_asha_cap_buckle_cap[];
extern Gfx asha_cap_Cap_DL_mesh_layer_1[];
extern Gfx asha_cap_material_revert_render_settings[];
