extern const GeoLayout asha_metalcap_6_Cap_Anim_State_Switch_opt1[];
extern const GeoLayout asha_metalcap_geo[];
extern Lights1 asha_metalcap_Metal__METAL__lights;
extern Lights1 asha_metalcap_belt_gold_lights;
extern Lights1 asha_metalcap_buckle_cap_lights;
extern u8 asha_metalcap_Metal_Shade_rgba16_rgba16[];
extern u8 asha_metalcap_Metal_Light_rgba16_rgba16[];
extern Vtx asha_metalcap_Metal_Cap_DL_mesh_layer_1_vtx_0[89];
extern Gfx asha_metalcap_Metal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx asha_metalcap_Metal_Cap_DL_mesh_layer_1_vtx_1[76];
extern Gfx asha_metalcap_Metal_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx asha_metalcap_Metal_Cap_DL_mesh_layer_1_vtx_2[6];
extern Gfx asha_metalcap_Metal_Cap_DL_mesh_layer_1_tri_2[];
extern Gfx mat_asha_metalcap_Metal__METAL_[];
extern Gfx mat_revert_asha_metalcap_Metal__METAL_[];
extern Gfx mat_asha_metalcap_belt_gold[];
extern Gfx mat_revert_asha_metalcap_belt_gold[];
extern Gfx mat_asha_metalcap_buckle_cap[];
extern Gfx mat_revert_asha_metalcap_buckle_cap[];
extern Gfx asha_metalcap_Metal_Cap_DL_mesh_layer_1[];
extern Gfx asha_metalcap_material_revert_render_settings[];
